# LightGBM Quantile Regression Model Configuration (q=0.5)

model:
  type: LGBMRegressor
  library: lightgbm
  parameters:
    n_estimators: 1000  # Increased for full training without early stopping
    max_depth: 10  # Limited depth to prevent overfitting and split warnings
    num_leaves: 100  # Maximum number of leaves per tree
    learning_rate: 0.1
    subsample: 0.8
    feature_fraction: 0.8  # LightGBM's version of colsample_bytree
    min_child_samples: 10  # Minimum samples per leaf to reduce overfitting
    random_state: 1986
    lambda_l1: 0.0  # L1 regularization
    lambda_l2: 1.0  # L2 regularization
    min_split_gain: 0.001  # Small minimum gain threshold to avoid -inf warnings
    n_jobs: -1  # Use all available CPU cores
    verbosity: -1  # Completely silent models during tuning to suppress warnings
    # Quantile regression specific parameters
    objective: 'quantile'
    alpha: 0.5  # Quantile level (0.5 = 50th percentile)
    eval_metric: 'quantile'

hypertuning:
  method: "halving_random_search"
  n_candidates: 30  # Reduced from 50
  parameters:
    max_depth: [6, 10, -1]  # Limited depth options, -1 for unlimited
    num_leaves: [31, 127]  # Constrained by max_depth (2^max_depth theoretical max)
    learning_rate: [0.01, 0.1, 0.2]  # Key learning rates
    n_estimators: [100, 300]  # Matching estimator counts
    subsample: [0.8, 1.0]  # Reasonable subsample
    feature_fraction: [0.8, 1.0]  # Reasonable feature fraction
    min_child_samples: [5, 20]  # Reasonable child sample counts
    lambda_l1: [0.0, 0.1]  # L1 regularization
    lambda_l2: [0.0, 1.0]  # L2 regularization
  cv: 3
  scoring:
    name: 'pinball_loss'
    alpha: 0.5
  n_jobs: 1
  factor: 3
  resource: 'n_samples'