# Quantile Forest Model Configuration (Random Forest for Quantile Regression)

model:
  type: RandomForestQuantileRegressor
  library: quantile_forest
  parameters:
    n_estimators: 300  # Reduced from 500 for faster training
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986
    n_jobs: -1  # Use all available CPU cores
    # Quantile-specific parameters
    default_quantiles: [0.9]  # Multiple quantiles can be predicted simultaneously

hypertuning:
  method: "halving_random_search"
  n_candidates: 25  # Reasonable candidate count
  parameters:
    n_estimators: [100, 300]  # Focused estimator range
    max_depth: [10, 20, None]  # Reasonable depth range
    min_samples_split: [2, 10]  # Reasonable split thresholds
    min_samples_leaf: [1, 5]  # Reasonable leaf sizes
    max_features: ['sqrt', None]  # Key feature selection options
    bootstrap: [True]  # Only bootstrap=True to avoid max_samples conflict
    max_samples: [0.6, 0.8, 1.0]  # Bootstrap sample fractions (only when bootstrap=True)
    # verbose parameter removed - not needed for tuning
  cv: 3
  scoring:
    name: 'pinball_loss'
    alpha: 0.9
  n_jobs: 1
  factor: 3
  resource: 'n_samples'