# Random Forest Classifier Model Configuration

model:
  type: RandomForestClassifier
  library: sklearn.ensemble
  parameters:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986
    verbose: 1  # Increased verbosity for progress information
    n_jobs: -1  # Use all available CPU cores

# Optional hyperparameter tuning configuration
hypertuning:
  method: "random_search"  # Options: "grid_search", "random_search"
  n_iter: 15  # Number of parameter combinations to try
  parameters:
    n_estimators: [50, 100, 200, 300, 500]
    max_depth: [None, 5, 10, 15, 20, 30]
    min_samples_split: [2, 5, 10, 15]
    min_samples_leaf: [1, 2, 4, 8]
    max_features: ['sqrt', 'log2', None]  # Added max_features for better optimization
    verbose: [0]  # Reduced verbosity for speed
  cv: 3  # Reduced from 5 to 3 for speed
  scoring:
    name: 'accuracy'
  n_jobs: 1  # Use single core to avoid joblib resource leaks