# Random Forest Classifier Model Configuration

model:
  type: RandomForestClassifier
  library: sklearn.ensemble
  parameters:
    n_estimators: 200  # Increased from 100 for better performance
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986
    verbose: 0  # Reduced verbosity for cleaner output
    n_jobs: -1  # Use all available CPU cores

hypertuning:
  method: "optuna"  # Using Optuna for optimization
  n_trials: 20  # Number of trials for Optuna
  direction: "maximize"  # For accuracy, higher is better
  parameters:
    n_estimators: {"type": "int", "low": 50, "high": 300, "step": 25}  # From 50 to 300 in steps of 25
    max_depth: {"type": "categorical", "choices": [null, 5, 10, 15, 20]}  # Include null for unlimited depth
    min_samples_split: {"type": "int", "low": 2, "high": 20}  # Min samples to split
    min_samples_leaf: {"type": "int", "low": 1, "high": 10}  # Min samples in leaf
    max_features: {"type": "categorical", "choices": ["sqrt", "log2", null]}  # Feature selection strategy
    bootstrap: {"type": "categorical", "choices": [true, false]}  # Bootstrap samples
  cv: 3  # Cross-validation folds
  scoring:
    name: 'accuracy'
  