# Random Forest Classifier Model Configuration

model:
  type: RandomForestClassifier
  library: sklearn.ensemble
  parameters:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986
    verbose: 1  # Increased verbosity for progress information
    n_jobs: -1  # Use all available CPU cores

# Optional hyperparameter tuning configuration
hypertuning:
  method: "grid_search"  # Options: "grid_search", "random_search"
  parameters:
    n_estimators: [50, 100]
    max_depth: [None, 10]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]
    verbose: [1]  # Keep verbosity during tuning
  cv: 5
  scoring:
    name: 'accuracy'
  n_jobs: -1  # Use all available CPU cores for parallel grid search