# Random Forest Classifier Model Configuration

model:
  type: RandomForestClassifier
  library: sklearn.ensemble
  parameters:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986
    verbose: 1  # Increased verbosity for progress information
    n_jobs: -1  # Use all available CPU cores

# Optional hyperparameter tuning configuration
hypertuning:
  method: "grid_search"  # Use basic grid search for hyperparameter tuning
  parameters:
    max_depth: [None, 5, 10, 20]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ['sqrt', 'log2', None]
    criterion: ['gini', 'entropy']
  cv: 3  # Cross-validation folds
  scoring:
    name: 'accuracy'
  n_jobs: -1  # Use all available CPU cores