# Random Forest Classifier Model Configuration

model:
  type: RandomForestClassifier
  library: sklearn.ensemble
  parameters:
    n_estimators: 200  # Increased from 100 for better performance
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986
    verbose: 0  # Reduced verbosity for cleaner output
    n_jobs: -1  # Use all available CPU cores

hypertuning:
  method: "grid_search"  # Simple grid search for demo
  parameters:
    n_estimators: [50, 100]  # Simple estimator options
    max_depth: [None, 10]  # Simple depth options
    min_samples_split: [2, 5]  # Simple split options
  cv: 3  # Cross-validation folds
  scoring:
    name: 'accuracy'
  