# Random Forest Classifier Model Configuration

model:
  type: RandomForestClassifier
  library: sklearn.ensemble
  parameters:
    n_estimators: 100
    max_depth: None
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 1986

# Optional hyperparameter tuning configuration
hypertuning:
  method: "grid_search"  # Options: "grid_search", "random_search"
  parameters:
    n_estimators: [50, 100, 200]
    max_depth: [None, 10, 20, 30]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  cv: 5
  scoring: 'accuracy'