# XGBoost Classifier Model Configuration

model:
  type: XGBClassifier
  library: xgboost
  parameters:
    n_estimators: 500  # Reduced from 1000 for faster training
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 1986
    verbosity: 0  # Silent mode
    n_jobs: -1  # Use all available CPU cores

hypertuning:
  method: "grid_search"  # Simple grid search for demo
  parameters:
    max_depth: [3, 6]  # Simple depth options
    learning_rate: [0.1, 0.2]  # Simple learning rate options
    n_estimators: [100, 200]  # Simple estimator options
  cv: 3  # Cross-validation folds
  scoring:
    name: 'accuracy'
  