# XGBoost Classifier Model Configuration

model:
  type: XGBClassifier
  library: xgboost
  parameters:
    n_estimators: 1000  # Increased for early stopping
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 1986
    verbosity: 1  # Reduced verbosity: 0=silent, 1=warning, 2=info, 3=debug
    n_jobs: -1  # Use all available CPU cores

# Optional hyperparameter tuning configuration
hypertuning:
  method: "grid_search"  # Use basic grid search for hyperparameter tuning
  parameters:
    max_depth: [3, 6, 10]
    learning_rate: [0.01, 0.1, 0.2]
    subsample: [0.7, 0.8, 1.0]
    colsample_bytree: [0.7, 0.8, 1.0]
    gamma: [0, 0.1]
  cv: 3  # Cross-validation folds
  scoring:
    name: 'accuracy'
  n_jobs: -1  # Use all available CPU cores