# Experiment Configuration Template

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/experiment.log"  # Optional log file path

# Data configuration
data:
  config_path: "ds_nailgun/configs/examples/data_config.yaml"  # Path to data configuration file

# Model configurations
models:
  config_paths:
    - "ds_nailgun/configs/model_presets/model_config_1.yaml"
    - "ds_nailgun/configs/model_presets/model_config_2.yaml"
    # Add more model configs as needed

# Output configuration
output:
  model_save_directory: "models/experiment/"  # Directory to save trained model pipelines
  save_format: "joblib"  # Options: joblib, pickle

# Experiment settings
experiment:
  name: "Experiment Name"
  description: "Description of the experiment"
  random_seed: 42