# Experiment Configuration Template
# This template shows how to configure experiments with multiple data and model configurations.
# The system will automatically create an experiment matrix: data_configs × model_configs
# Example: 2 data configs × 3 model configs = 6 total experiments

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/experiment.log"  # Optional log file path

# Data configurations - supports multiple data configs for comprehensive experimentation
data:
  config_paths:
    - "ds_nailgun/configs/examples/data_config.yaml"  # First data configuration
    - "ds_nailgun/configs/examples/data_config_alt.yaml"  # Second data configuration (optional)
    # Add more data configs to create experiment matrix: data_configs × model_configs

# Model configurations - each model will be trained on each data configuration
models:
  config_paths:
    - "ds_nailgun/configs/model_presets/model_config_1.yaml"
    - "ds_nailgun/configs/model_presets/model_config_2.yaml"
    # Add more model configs as needed - each will be combined with each data config

# Output configuration
output:
  base_directory: "experiments/"  # Base directory for experiment outputs
  # The system will create a timestamped folder: experiments/experiment_name_20250123_143022/
  # This folder will contain: models/, logs/, results/, and config_summary.yaml

# Experiment settings
experiment:
  name: "Experiment Name"
  description: "Description of the experiment - will run data_configs × model_configs experiments"
  random_seed: 42