# Model Configuration Template
# This template shows all available options for configuring a model in Data-Science-Nailgun
# Copy this file and customize it for your specific model

# Model configuration section - defines the model type and parameters
model:
  # Model class name (e.g., RandomForestClassifier, RandomForestRegressor, LogisticRegression, LinearRegression)
  type: "RandomForestClassifier"
  # Library/module where the model is located (e.g., sklearn.ensemble, sklearn.linear_model)
  library: "sklearn.ensemble"
  # Model parameters - these are passed directly to the model constructor
  parameters:
    # Common parameters for RandomForest models
    n_estimators: 100  # Number of trees in the forest
    max_depth: null    # Maximum depth of the tree (null for unlimited)
    min_samples_split: 2  # Minimum samples required to split an internal node
    min_samples_leaf: 1   # Minimum samples required to be at a leaf node
    random_state: 42     # Random state for reproducibility
    # Add other model-specific parameters as needed
    # For example, for LogisticRegression:
    # C: 1.0
    # penalty: "l2"

# Optional hyperparameter tuning configuration - for automated parameter optimization
hypertuning:
  # Tuning method: "grid_search" for exhaustive search, "random_search" for randomized sampling
  method: "grid_search"
  # Parameter space to search - lists for grid search, can also include distributions for random search
  parameters:
    # Example parameters for RandomForest tuning
    n_estimators: [50, 100, 200]
    max_depth: [null, 10, 20, 30]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    # For regression models, you might tune:
    # max_features: ["auto", "sqrt", "log2"]
  # Cross-validation folds
  cv: 5
  # Scoring metric - depends on problem type
  # For classification: "accuracy", "f1", "precision", "recall", "roc_auc"
  # For regression: "neg_mean_squared_error", "neg_mean_absolute_error", "r2"
  scoring: "accuracy"
  # Number of iterations for random search (ignored for grid search)
  n_iter: 10</content>  # Only used for random_search