# Quantile Regression Test Experiment Configuration

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/quantile_test_experiment.log"  # Optional log file path

# Data configurations - using Titanic data for testing (treating as regression)
data:
  config_paths:
    - "ds_nailgun/configs/examples/titanic_data_config.yaml"

# Model configurations - all quantile regression models
models:
  config_paths:
    - "ds_nailgun/configs/model_presets/lightgbm_quantile_config.yaml"
    - "ds_nailgun/configs/model_presets/xgboost_quantile_config.yaml"
    - "ds_nailgun/configs/model_presets/catboost_quantile_config.yaml"
    - "ds_nailgun/configs/model_presets/gradient_boosting_quantile_config.yaml"
    - "ds_nailgun/configs/model_presets/extra_trees_quantile_config.yaml"
    - "ds_nailgun/configs/model_presets/quantile_forest_config.yaml"
    - "ds_nailgun/configs/model_presets/quantile_regressor_config.yaml"

# Output configuration
output:
  base_directory: "experiments/"  # Base directory for experiment outputs
  save_format: "joblib"  # Options: joblib, pickle

# Experiment settings
experiment:
  name: "Quantile Regression Model Test"
  description: "Testing all quantile regression models at 0.9 quantile level"
  random_seed: 1986