# Titanic Dataset Configuration

files:
  train_data: ds_nailgun/data/titanic/train.csv
  test_data: ds_nailgun/data/titanic/test.csv
  validation_data: null  # Optional validation data location

data:
  id:
    column: "PassengerId"
  target:
    column: "Survived"
    classes: 2  # Number of classes. If classes is 0, then this is a regression problem
  features:
    # Passenger class and family information (ordinal/categorical integers)
    passenger_info:
      - "Pclass"
      - "SibSp"
      - "Parch"
    # Continuous numerical features
    continuous_features:
      - "Age"
      - "Fare"
    # Categorical string features
    categorical_features:
      - "Sex"
      - "Embarked"

preprocessing:
  imputation:
    passenger_info:
      method: "median"
    continuous_features:
      method: "mean"
    categorical_features:
      method: "constant"
      fill_value: "missing"
  transforms:
    continuous_features:
      method: "standard_scaler"
    categorical_features:
      method: "one_hot_encoding"
  feature_selection:
    method: "select_k_best"
    params:
      k: 5
      score_func: "f_classif"