# Titanic Experiment Configuration

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/titanic_experiment.log"  # Optional log file path

# Data configuration
data:
  config_path: "ds_nailgun/configs/examples/titanic_data_config.yaml"

# Model configurations
models:
  config_paths:
    - "ds_nailgun/configs/model_presets/random_forest_classifier_config.yaml"
    - "ds_nailgun/configs/model_presets/xgboost_classifier_config.yaml"

# Output configuration
output:
  model_save_directory: "models/titanic_experiment/"  # Directory to save trained model pipelines
  save_format: "joblib"  # Options: joblib, pickle

# Experiment settings
experiment:
  name: "Titanic Survival Prediction"
  description: "Predicting passenger survival on the Titanic using Random Forest and XGBoost"
  random_seed: 1986