version: "1.0"

name: "XGBoost-Basic"
model: "xgbc"
estimator: "xgboost.XGBClassifier"
params:
  random_state: 42
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 1.0

search:
  common:
    # shared search choices used by both grid and randomized search
    n_estimators: [50, 100, 200, 400]
    max_depth: [3, 6, 8, 10]
    learning_rate: [0.01, 0.05, 0.1, 0.2]
    subsample: [0.5, 0.7, 0.8, 1.0]
    colsample_bytree: [0.5, 0.7, 0.8, 1.0]
    reg_alpha: [0.0, 0.01, 0.1]
    reg_lambda: [0.1, 1.0, 10.0]
    min_child_weight: [1, 3, 5]
    gamma: [0.0, 0.1, 0.5]

  grid:
    include_common: true
    # grid-specific overrides (leave empty to use common)
    overrides: {}

  distributions:
    include_common: true
    # randomized-search-friendly overrides; dicts indicate distribution hints
    overrides:
      learning_rate: {"dist": "loguniform", "low": 1e-3, "high": 0.3}
      n_estimators: [50, 100, 200, 400, 800]
      max_depth: [3, 4, 6, 8, 10]
      subsample: {"dist": "uniform", "low": 0.4, "high": 1.0}
      colsample_bytree: {"dist": "uniform", "low": 0.4, "high": 1.0}
      reg_alpha: {"dist": "loguniform", "low": 1e-6, "high": 1.0}
      reg_lambda: {"dist": "loguniform", "low": 1e-3, "high": 10.0}
      min_child_weight: [1, 3, 5, 10]
      gamma: {"dist": "uniform", "low": 0.0, "high": 1.0}
